 version: 1.1

 orbs:
  win: circleci/windows@2.2.0

 jobs:
   build:
     executor: machine
    
     steps:
       - checkout
       - run: dotnet build
       - run: sudo apt-get install mongodb-clients
